<?php require_once __DIR__ . "/layout/header.php" ?>

<div class="container">
    <section class="auth">
        <div class="row">
            <h2>Регистрация</h2>
            <div class="col-md-12">
                <form method="POST" action="/user/register">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Почта</label>
                        <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
                        <?php if(isset($errors['email'])): ?>
                            <small id="emailHelp" class="form-text text-danger"><?= $errors['email'] ?></small>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Пароль</label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль">
                        <?php if(isset($errors['password'])): ?>
                            <small id="emailHelp" class="form-text text-danger"><?= $errors['password'] ?></small>
                        <?php endif; ?>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Отправить</button>
                </form>
            </div>
        </div>

    </section>
</div>

</body>
</html>